// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZOoqzE232lSNLz0P3SHvPi2_-cqrSPyo',
    appId: '1:1089540674888:web:d2afc1facd7539a7234f7d',
    messagingSenderId: '1089540674888',
    projectId: 'ph-monitor-app',
    authDomain: 'ph-monitor-app.firebaseapp.com',
    storageBucket: 'ph-monitor-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuResZ3yDUAyuVY1RIe_NoWNOsAhaxR84',
    appId: '1:1089540674888:android:d94c7f8c2338c760234f7d',
    messagingSenderId: '1089540674888',
    projectId: 'ph-monitor-app',
    storageBucket: 'ph-monitor-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqD5auatWNYM959qKj4E0bdJtkBOzt9EQ',
    appId: '1:1089540674888:ios:3af1d4edc2358d21234f7d',
    messagingSenderId: '1089540674888',
    projectId: 'ph-monitor-app',
    storageBucket: 'ph-monitor-app.appspot.com',
    iosBundleId: 'com.example.monitorph',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqD5auatWNYM959qKj4E0bdJtkBOzt9EQ',
    appId: '1:1089540674888:ios:60385baefc4b9915234f7d',
    messagingSenderId: '1089540674888',
    projectId: 'ph-monitor-app',
    storageBucket: 'ph-monitor-app.appspot.com',
    iosBundleId: 'com.example.monitorph.RunnerTests',
  );
}
